#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# TIP multi Displays
# https://protesilaos.com/codelog/multihead-bspwm-polybar/

~/.config/dunst/load.sh &
~/.config/polybar/launch.sh &

bspc config border_width 2
bspc config window_gap 10
bspc config focused_border_color "#5E81AC"
bspc config normal_border_color "#4c566a"
bspc config focus_follows_pointer true
bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle false
bspc config focus_by_distance true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

bspc rule -a firefox desktop='^10' follow=off
bspc rule -a Zathura state=tiled

# Reoader workspaces. This some script is run with posthook autorandr
/home/gameboy/.config/bspwm/scripts/./bspwm_reorder
