#!/usr/bin/zsh

while [ "$#" -gt 0 ]; do
    curr=$1
    shift
    case "$curr" in
    "-n")
        prime-run $HOME/GOG\ Games/Icewind\ Dale\ Enhanced\ Edition/start.sh
        ;;
    *)
        echo "Options not recognized"
        ;;
    esac
done

if [ "$#" -eq 0 ]
then
    $HOME/GOG\ Games/Icewind\ Dale\ Enhanced\ Edition/start.sh
fi
