format = """
$hostname\
$directory\
$fill\
$git_branch\
$git_commit\
$git_state\
$git_status\
$kubernetes\
$docker_context\
$golang\
$lua\
$python\
$solidity\
$jobs\
$status\
$time\
\n\
$cmd_duration\
$sudo\
$character\
"""

palette = 'gruvbox_dark'
continuation_prompt = '❯'

[fill]
symbol = " "

[palettes.gruvbox_dark]
color_fg0 = '#fbf1c7'
color_bg1 = '#3c3836'
color_bg3 = '#665c54'
color_blue = '#458588'
color_aqua = '#689d6a'
color_green = '#98971a'
color_orange = '#d65d0e'
color_purple = '#b16286'
color_red = '#cc241d'
color_yellow = '#d79921'
color_snow = '#e5e9f0'
color_snow_2 = '#d8dee9'

[kubernetes]
disabled = false

[hostname]
ssh_only = true
format = ' [SSH on $hostname](bold color_orange)'
disabled = false

[character]
format = "$symbol "
success_symbol = "[ ❯](bold color_aqua)"
error_symbol = "[ ❯](color_red)"

[env_var.VIMSHELL] # vim subshell
format = "[$env_value]($style)"
style = 'green italic'

[sudo]
format = " [$symbol]($style)"
style = "italic bright-purple"
symbol = "\uea6a"
disabled = false

[directory]
truncation_length = 3
# truncation_symbol = "…/"
# truncation_symbol = ".../"
truncate_to_repo = true
read_only = "󰌾"
style = "fg:color_snow italic bold"
format = ' [$path]($style) [$read_only]($read_only_style)'
# format = " [\ueaed \\[[$path]($style) [$read_only]($read_only_style)\\]](color_blue)"

[cmd_duration]
min_time = 500
format = "[$duration](italic bright-yellow)"

[jobs]
format = "[ $symbol$number]($style)"
style = "white"
symbol = "[ ](blue italic)"

[time]
disabled = false
format = " [ $time]($style)"
time_format = "%R"
utc_time_offset = "local"
style = "bold fg:color_purple"

[git_branch]
# format = "[ \\[$symbol [$branch(:$remote_branch)](bold italic fg:color_bg3)\\]]($style)"
format = "[ \\[$symbol [$branch(:$remote_branch)](bold italic fg:color_bg3)\\]]($style)"
symbol = "[\ue702](bold color_orange)"
style = "bold color_bg3"

[git_status]
style = 'fg:color_red bold'

[lua]
symbol = "\ue620 "
format = " [${symbol}${version}]($style)"
style = "italic color_blue"

[python]
symbol = "\ue73c "
format = " [${symbol}${version}]($style)"
version_format = "${major}.${minor}"
style = "italic color_blue"

[docker_context]
symbol = "\uf21f "
style = "italic color_blue"
format = " [$symbol$context]($style)"

[golang]
symbol = "[\ue627](color_blue) "
style = "italic color_blue"
format = " [$symbol($version )]($style)"
