export PAGER='nvim -R'
export EDITOR='nvim'
export VISUAL='nvim'
export ZSH=/usr/share/oh-my-zsh/
export ZSH_THEME="agnoster"
export ZSH_TMUX_AUTOSTART=true
export ZSH_TMUX_AUTOCONNECT=false
export ZSH_TMUX_AUTOQUIT=false
export ZSH_TMUX_CONFIG=".config/tmux/tmux.conf"
